
package workflow.orchestrator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Orchestrator", targetNamespace = "http://orchestrator.workflow")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Orchestrator {


    /**
     * 
     * @param position
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startprocess", targetNamespace = "http://orchestrator.workflow", className = "workflow.orchestrator.Startprocess")
    @ResponseWrapper(localName = "startprocessResponse", targetNamespace = "http://orchestrator.workflow", className = "workflow.orchestrator.StartprocessResponse")
    public boolean startprocess(
        @WebParam(name = "position", targetNamespace = "")
        String position);

}
