
package workflow.interviewerdop;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "interviewerDOP", targetNamespace = "http://interviewerDOP.workflow")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InterviewerDOP {


    /**
     * 
     * @param role
     * @param beancandidat
     * @return
     *     returns workflow.interviewerdop.Beancandidat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "execstep", targetNamespace = "http://interviewerDOP.workflow", className = "workflow.interviewerdop.Execstep")
    @ResponseWrapper(localName = "execstepResponse", targetNamespace = "http://interviewerDOP.workflow", className = "workflow.interviewerdop.ExecstepResponse")
    public Beancandidat execstep(
        @WebParam(name = "role", targetNamespace = "")
        String role,
        @WebParam(name = "beancandidat", targetNamespace = "")
        Beancandidat beancandidat);

}
