
package workflow.accessdb;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Accessdb", targetNamespace = "http://accessdb.workflow")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Accessdb {


    /**
     * 
     * @return
     *     returns java.util.List<workflow.accessdb.BeanProcess>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListstep", targetNamespace = "http://accessdb.workflow", className = "workflow.accessdb.GetListstep")
    @ResponseWrapper(localName = "getListstepResponse", targetNamespace = "http://accessdb.workflow", className = "workflow.accessdb.GetListstepResponse")
    public List<BeanProcess> getListstep();

}
