
package workflow.accessdb;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Accessdb", targetNamespace = "http://accessdb.workflow")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Accessdb {


    /**
     * 
     * @param candidat
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setCandidat", targetNamespace = "http://accessdb.workflow", className = "workflow.accessdb.SetCandidat")
    @ResponseWrapper(localName = "setCandidatResponse", targetNamespace = "http://accessdb.workflow", className = "workflow.accessdb.SetCandidatResponse")
    public boolean setCandidat(
        @WebParam(name = "candidat", targetNamespace = "")
        Beancandidat candidat);

    /**
     * 
     * @param candidat
     * @return
     *     returns workflow.accessdb.Beancandidat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCandidat", targetNamespace = "http://accessdb.workflow", className = "workflow.accessdb.GetCandidat")
    @ResponseWrapper(localName = "getCandidatResponse", targetNamespace = "http://accessdb.workflow", className = "workflow.accessdb.GetCandidatResponse")
    public Beancandidat getCandidat(
        @WebParam(name = "candidat", targetNamespace = "")
        int candidat);

    /**
     * 
     * @return
     *     returns java.util.List<workflow.accessdb.BeanProcess>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListstep", targetNamespace = "http://accessdb.workflow", className = "workflow.accessdb.GetListstep")
    @ResponseWrapper(localName = "getListstepResponse", targetNamespace = "http://accessdb.workflow", className = "workflow.accessdb.GetListstepResponse")
    public List<BeanProcess> getListstep();

    /**
     * 
     * @param position
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "initprocess", targetNamespace = "http://accessdb.workflow", className = "workflow.accessdb.Initprocess")
    @ResponseWrapper(localName = "initprocessResponse", targetNamespace = "http://accessdb.workflow", className = "workflow.accessdb.InitprocessResponse")
    public Integer initprocess(
        @WebParam(name = "position", targetNamespace = "")
        String position);

}
