
package workflow;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Registry", targetNamespace = "http://workflow")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Registry {


    /**
     * 
     * @param servicename
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getService", targetNamespace = "http://workflow", className = "workflow.GetService")
    @ResponseWrapper(localName = "getServiceResponse", targetNamespace = "http://workflow", className = "workflow.GetServiceResponse")
    public String getService(
        @WebParam(name = "servicename", targetNamespace = "")
        String servicename);

    /**
     * 
     * @param servicename
     * @param url
     */
    @WebMethod
    @RequestWrapper(localName = "addService", targetNamespace = "http://workflow", className = "workflow.AddService")
    @ResponseWrapper(localName = "addServiceResponse", targetNamespace = "http://workflow", className = "workflow.AddServiceResponse")
    public void addService(
        @WebParam(name = "servicename", targetNamespace = "")
        String servicename,
        @WebParam(name = "url", targetNamespace = "")
        String url);

}
